### PR TITLE
Get all names from feed items: optimisation

### PR DESCRIPTION
**Pull request by byblik**
array_merge spends several minutes to merge all namespaces on ~40k items which was quite unacceptable.
Replaced slow array_merge with array element assignment with uniqueness check which is enough in this case. 
Now it spends 2 seconds on ~40k items on my machine.

### CODE REVIEW

**Comment by mibe** [comment]
Do you really use FeedWriter with 40k elements or was that just for testing?

**Comment by byblik** [comment]
Yes, really used.

**Comment by mrafeeq** [comment]
Yes jobsRmine uses it , some of our feeds are really long. e.ge., https://www.jobsrmine.com/rss-us.xml

**Comment by mibe** [comment]
Wow, I'm impressed. That's pretty cool. :smiley:

**Pull request merged**
