### PR TITLE
How to create rss for open cart?

### PR DESCRIPTION
**Pull request by NeoCsatornaja**
Hy!
I would like to create rss chanel for open cart with this structure:
http://pastebin.com/SuwdvMTj
Can you help me please?

### CODE REVIEW

**Comment by mibe** [comment]
That depends how you want to structure your feed - which content from the XML should be the feed item title / description?

This example puts the manufacturer and name in the title element and the category in the description:

    $newItem->setTitle($manufacturer . ' ' . $name);
    $newItem->setLink($product_url);
    $newItem->setDescription($category);
    $newItem->setDate(time());

**Comment by mibe** [comment]
No further response in four weeks: closing.

**Comment by NeoCsatornaja** [comment]
Sorry, I dosen' get any mail, just now!
Yes, this xml struketure need!

**Comment by mibe** [comment]
@NeoCsatornaja: Here's an example of how to use the FeedWriter classes. Your job is to include this in your code (make sure to include the `Feed.php`, `Item.php` and `RSS2.php` files, or better, use an autoloader), iterate through your data (I exemplary included a for loop) and fill the variables with your OpenCart data.

```php
$feed = new RSS2;

$feed->setTitle('Your title here');
$feed->setLink('http://www.example.com');
$feed->setDescription('Your description here');


// Iterate through your data here...
// for($i = 0; $i < $count; $i++)
// {
	$newItem = $feed->createNewItem();

	// Fill these variables with your XML data from OpenCart:
	// $manufacturer = ...
	// $name = ...
	// $product_url = ...
	// $category = ...
	
	$newItem->setTitle($manufacturer . ' ' . $name);
	$newItem->setLink($product_url);
	$newItem->setDescription($category);
	$newItem->setDate(time());

	$feed->addItem($newItem);
// }

$feed->printFeed();
```

**Comment by NeoCsatornaja** [comment]
Good lord thank you!
I have one quetion:
We have latin2 characterrs for example:
Áéű, etc thats create any problem ön feed?

**Comment by mibe** [comment]
That should work as long as you set the encoding of the resulting XML to `ISO-8859-2`. You can achieve that by calling `$feed->setEncoding('ISO-8859-2');` before generating the feed.
But there may be a problem with that: It looks like the filter for removing [invalid XML characters](http://www.w3.org/TR/REC-xml/#charsets) is also happily removing not only these ISO 8859-2 chars, but the whole filter input! This looks like a bug to me. I'm currently investigating this.
Anyway for maximised client compatibility you should actually use UTF-8. The best would probably be to convert your text data to UTF-8.

**Comment by NeoCsatornaja** [comment]
And How can I do that?
You thinkibg about php escape őr spmethong like that?

**Comment by mibe** [comment]
You can convert character encodings with the [`iconv`](http://php.net/manual/en/function.iconv.php) function:

```php
$content = iconv('ISO-8859-2', 'UTF-8//TRANSLIT', $content);
```

**Comment by mibe** [comment]
Hey @NeoCsatornaja,
I just commited a new branch which should fix the encoding problem mentioned above. If you want you can give it a try with 9e0106ef9121397b8971796d9a93c73a34d0da93.

**Comment by NeoCsatornaja** [comment]
Thank you but now I worked  at athoner company so, I don't need that code in this time.
But I should come back as soon when I need it.
I appreciate your work, thank you!

**Pull request closed without merging**
