### PR TITLE
Avoid "Invalid argument supplied for foreach()" warning

### PR DESCRIPTION
**Pull request by antoniocoratelli**

### CODE REVIEW

**Comment by mibe** [comment]
I'd like to reproduce this bug. Could you give some example code? Because `$value`, which is iterated in the `foreach` loop, should always be an array.

**Comment by antoniocoratelli** [comment]
Of course, I'll send you the code as soon as I return home.

Anyway it's very basic. I instantiate a new FeedWriter\RSS2, set feed title
and add a bunch of items (with title, link, date and description) in a for
loop, then echo the generated feed.

Please note that the "bug" it's just a warning, and my php.ini is set to
display all error messages (E_ALL).
I think the warning is just caused by `$value` being empty.

**Comment by antoniocoratelli** [comment]
Here's the code

```
public static function toRSS() {
	$FeedGen = new \FeedWriter\RSS2;
	$FeedGen->setTitle('Error Feed');
	
	$q = self::$db->prepare("SELECT * FROM log ORDER BY timestamp DESC");
	if (!$q) throw new GE("Can't prepare query");
	$r = $q->execute();
	if (!$r) throw new GE("Can't exec query");

	$empty = true;
	while ($i = $r->fetchArray(SQLITE3_ASSOC)) {
		$empty = false;
		$FeedGenItem = $FeedGen->createNewItem();
		$FeedGenItem->setTitle($i['string']);
		$FeedGenItem->setLink($i['file']);
		$FeedGenItem->setDate($i['timestamp']);
		$FeedGenItem->setDescription($i['message']);
		$FeedGen->addItem($FeedGenItem);
	}
	return  ($empty)? '' : $FeedGen->generateFeed();
}
```

**Comment by mibe** [comment]
Thanks for providing the code. If fixed the underlying cause in 73b6870 and released version 1.0.4.

If you cannot somehow update to this version, the workaround is to call the `setLink()` method of the feed instance, providing some sort of URL:
```php
$FeedGen->setLink('http://example.com');
```
Thanks for finding this bug! :+1:

**Pull request closed without merging**
